# Generated by Django 5.2.14 on 2026-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_human_gated_runtime'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deferredworkflowexecution',
            new_name='workflows_d_status_3790a5_idx',
            old_name='workflows__status_8e49c0_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowapprovalrecord',
            new_name='workflows_w_status_7ae6cf_idx',
            old_name='workflows__status_a91d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowapprovalrecord',
            new_name='workflows_w_workflo_5d8d64_idx',
            old_name='workflows__workflo_0aa786_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowimprovementsuggestion',
            new_name='workflows_w_user_id_018385_idx',
            old_name='workflows__user_id_6abce3_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowimprovementsuggestion',
            new_name='workflows_w_workflo_7fadf8_idx',
            old_name='workflows__workflo_605af4_idx',
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
