# Generated by Django 5.2.14 on 2026-06-09 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(default='x', max_length=20)),
                ('tier', models.CharField(choices=[('macro', 'Macro'), ('mid', 'Mid'), ('micro', 'Micro')], default='micro', max_length=10)),
                ('followers', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_muted', models.BooleanField(default=False)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='SignetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Signet activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField()),
                ('edge_type', models.CharField(choices=[('SEEDS', 'Seeds'), ('AMPLIFIES', 'Amplifies'), ('TAGGED_WITH', 'Tagged With'), ('SPREADS_VIA', 'Spreads Via'), ('PART_OF_NETWORK', 'Part of Network')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_edges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignetHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('volume', models.IntegerField(default=0)),
                ('velocity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('peak', 'Peak')], default='low', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_hashtags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-volume'],
            },
        ),
        migrations.CreateModel(
            name='SignetNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reach', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('decaying', 'Decaying'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_narratives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reach'],
            },
        ),
        migrations.CreateModel(
            name='SignetReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('GATE 1', 'Gate 1 — Routine'), ('GATE 2', 'Gate 2 — Sensitive')], default='GATE 1', max_length=10)),
                ('verdict_tag', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('tier', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('excerpt', models.TextField()),
                ('reason', models.TextField()),
                ('model_name', models.CharField(default='claude-sonnet/post_tagger_1.2', max_length=100)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
