# Generated by Django 5.2.14 on 2026-06-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_ingestion_record_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION block_ingestion_record_update()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'IngestionRecord is immutable and cannot be updated. id=%', OLD.id;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER ingestion_record_immutable_trigger
        BEFORE UPDATE ON signet_ingestionrecord
        FOR EACH ROW EXECUTE FUNCTION block_ingestion_record_update();
    """)


def drop_ingestion_record_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        DROP TRIGGER IF EXISTS ingestion_record_immutable_trigger ON signet_ingestionrecord;
        DROP FUNCTION IF EXISTS block_ingestion_record_update();
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='reddit', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused')], default='idle', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_collection_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_post_id', models.CharField(max_length=100)),
                ('platform_author_id', models.CharField(max_length=100)),
                ('author_handle', models.CharField(max_length=100)),
                ('content_text', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('reach', models.IntegerField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('is_reply', models.BooleanField(default=False)),
                ('is_repost', models.BooleanField(default=False)),
                ('parent_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('collector_version', models.CharField(default='1.0', max_length=20)),
                ('tagging_status', models.CharField(choices=[('pending', 'Pending'), ('tagged', 'Tagged'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_collected_posts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_posts', to='signet.collectionsession')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['platform', 'platform_post_id'], name='signet_coll_platfor_f0d3ed_idx'), models.Index(fields=['tagging_status'], name='signet_coll_tagging_1548bf_idx'), models.Index(fields=['session'], name='signet_coll_session_64020d_idx')],
                'unique_together': {('platform', 'platform_post_id')},
            },
        ),
        migrations.CreateModel(
            name='IngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_post_id', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_records', to='signet.collectionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_ingestion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['platform', 'platform_post_id'], name='signet_inge_platfor_26c1d1_idx'), models.Index(fields=['session'], name='signet_inge_session_f69396_idx')],
                'unique_together': {('platform', 'platform_post_id')},
            },
        ),
        migrations.RunPython(create_ingestion_record_trigger, drop_ingestion_record_trigger),
    ]
