# Generated by Django 5.2.14 on 2026-06-14 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0002_collectionsession_collectedpost_ingestionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('confidence_tier', models.CharField(default='low', max_length=10)),
                ('prompt_version', models.CharField(max_length=50)),
                ('model_version', models.CharField(default='', max_length=50)),
                ('llm_call_id', models.CharField(blank=True, default='', max_length=100)),
                ('raw_llm_response', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('auto_eligible', 'Auto Eligible'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='signet.collectedpost')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='signet.collectionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_post_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post'], name='signet_post_post_id_fd74ae_idx'), models.Index(fields=['review_status'], name='signet_post_review__7e5818_idx'), models.Index(fields=['confidence_tier'], name='signet_post_confide_b5e651_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION block_post_classification_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION 'PostClassification is immutable. Create a new versioned row instead of updating. id=%', OLD.id;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER post_classification_immutable_trigger
                BEFORE UPDATE ON signet_postclassification
                FOR EACH ROW EXECUTE FUNCTION block_post_classification_update();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS post_classification_immutable_trigger ON signet_postclassification;
                DROP FUNCTION IF EXISTS block_post_classification_update();
            """,
        ),
    ]
