# Generated by Django 5.2.14 on 2026-06-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0003_postclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postclassification',
            name='signet_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='signet.signetreviewitem'),
        ),
    ]
