# Generated by Django 5.2.15 on 2026-06-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0005_ingestionrecord_immutable_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='postclassification',
            name='entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postclassification',
            name='novelty_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postclassification',
            name='novelty_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postclassification',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postclassification',
            name='themes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signetnarrative',
            name='entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signetnarrative',
            name='themes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
