# Generated by Django 5.2.15 on 2026-06-16 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0006_postclassification_entities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signetnarrative',
            unique_together={('user', 'label')},
        ),
    ]
