# Generated by Django 5.2.15 on 2026-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0007_alter_signetnarrative_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postclassification',
            name='safety_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='postclassification',
            name='safety_excluded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
