# Generated by DeepSeek — Chunk 1 coordination graph layer
# QA fix (Claude): FK must target settings.AUTH_USER_MODEL, not the hardcoded
# 'users.user' label, which Django cannot resolve (migrate crashed on it).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signet', '0008_postclassification_safety_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignetCoordinationCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('account_ids', models.JSONField(blank=True, default=list)),
                ('axes', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(default=0.0)),
                ('size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('decaying', 'Decaying'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signet_coordination_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'label')},
            },
        ),
    ]
