# Generated by Django 5.2.14 on 2026-06-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_bookingreference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='provider',
            field=models.CharField(choices=[('buupass', 'Buupass'), ('booking', 'Booking.com'), ('amadeus', 'Amadeus'), ('duffel', 'Duffel'), ('karibu', 'Karibu Taxi'), ('eventbrite', 'Eventbrite')], max_length=50),
        ),
    ]
