# Generated by Django 6.0.4 on 2026-06-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_chatroom_domain_chatroom_name'),
        ('travel', '0004_alter_searchcache_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='chatroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary', to='chatbot.chatroom'),
        ),
    ]
