import type { SignetNode, SignetEdge, ActivityItem, ReviewItem } from './types'

export const NODES: SignetNode[] = [
  { id: 'acc_001', type: 'account', handle: '@KE_Wakili', tier: 'macro', tags: ['red_pill_pipeline', 'anti_institution'], followers: 89400, posts: 342, confidence: 0.91, platform: 'x' },
  { id: 'acc_002', type: 'account', handle: '@NairobiTruth_KE', tier: 'macro', tags: ['firehose_falsehood', 'political_disinfo'], followers: 124000, posts: 891, confidence: 0.87, platform: 'x' },
  { id: 'acc_003', type: 'account', handle: '@Rift_Patriot', tier: 'mid', tags: ['identity_wedge', 'coordinated_inauthentic'], followers: 34200, posts: 214, confidence: 0.78, platform: 'x' },
  { id: 'acc_004', type: 'account', handle: '@254_Analyst', tier: 'mid', tags: ['political_disinfo'], followers: 22100, posts: 156, confidence: 0.65, platform: 'x' },
  { id: 'acc_005', type: 'account', handle: '@KenyaWatchdog', tier: 'mid', tags: ['appeal_to_victimhood'], followers: 18700, posts: 203, confidence: 0.72, platform: 'x' },
  { id: 'acc_006', type: 'account', handle: '@MtaaAnalyst', tier: 'mid', tags: ['red_pill_pipeline'], followers: 15300, posts: 178, confidence: 0.81, platform: 'x' },
  { id: 'acc_007', type: 'account', handle: '@SavannahPulse', tier: 'mid', tags: ['coordinated_inauthentic'], followers: 28900, posts: 445, confidence: 0.69, platform: 'x' },
  { id: 'acc_008', type: 'account', handle: '@citizen_k254', tier: 'micro', tags: [], followers: 892, posts: 34, confidence: 0.30, platform: 'x' },
  { id: 'acc_009', type: 'account', handle: '@nairobi_mwananchi', tier: 'micro', tags: ['appeal_to_victimhood'], followers: 2100, posts: 67, confidence: 0.44, platform: 'x' },
  { id: 'acc_010', type: 'account', handle: '@eastafrica_now', tier: 'micro', tags: [], followers: 1340, posts: 23, confidence: 0.28, platform: 'x' },
  { id: 'acc_011', type: 'account', handle: '@ke_observer_9', tier: 'micro', tags: ['coordinated_inauthentic'], followers: 445, posts: 89, confidence: 0.83, platform: 'x' },
  { id: 'acc_012', type: 'account', handle: '@kenyapolitics24', tier: 'micro', tags: ['coordinated_inauthentic'], followers: 677, posts: 112, confidence: 0.79, platform: 'x' },
  { id: 'nar_001', type: 'narrative', label: 'Election System Compromised', tags: ['election_integrity', 'coordinated_amplified'], reach: 234000, confidence: 0.88, status: 'active' },
  { id: 'nar_002', type: 'narrative', label: 'IMF Debt Trap Narrative', tags: ['economic_fear', 'firehose_falsehood'], reach: 189000, confidence: 0.82, status: 'active' },
  { id: 'nar_003', type: 'narrative', label: 'Foreign NGO Interference', tags: ['anti_institution', 'political_disinfo'], reach: 145000, confidence: 0.74, status: 'decaying' },
  { id: 'nar_004', type: 'narrative', label: 'Ethnic Land Grievance Reframe', tags: ['identity_wedge', 'appeal_to_victimhood'], reach: 98000, confidence: 0.91, status: 'active' },
  { id: 'nar_005', type: 'narrative', label: 'Vaccine Microchip Revival', tags: ['health_misinfo'], reach: 67000, confidence: 0.95, status: 'decaying' },
  { id: 'tag_001', type: 'hashtag', label: '#KenyaDecides', volume: 45200, velocity: 'high', tags: [] },
  { id: 'tag_002', type: 'hashtag', label: '#IMFGoHome', volume: 38900, velocity: 'high', tags: [] },
  { id: 'tag_003', type: 'hashtag', label: '#RutoMustGo', volume: 89400, velocity: 'peak', tags: [] },
  { id: 'tag_004', type: 'hashtag', label: '#WakiliSpeaks', volume: 12300, velocity: 'medium', tags: [] },
  { id: 'tag_005', type: 'hashtag', label: '#254Truth', volume: 8900, velocity: 'low', tags: [] },
]

export const EDGES: SignetEdge[] = [
  { source: 'acc_001', target: 'nar_001', type: 'SEEDS' },
  { source: 'acc_002', target: 'nar_002', type: 'SEEDS' },
  { source: 'acc_001', target: 'nar_004', type: 'SEEDS' },
  { source: 'acc_003', target: 'nar_004', type: 'SEEDS' },
  { source: 'acc_002', target: 'nar_003', type: 'SEEDS' },
  { source: 'acc_004', target: 'nar_001', type: 'AMPLIFIES' },
  { source: 'acc_005', target: 'nar_001', type: 'AMPLIFIES' },
  { source: 'acc_006', target: 'nar_002', type: 'AMPLIFIES' },
  { source: 'acc_007', target: 'nar_002', type: 'AMPLIFIES' },
  { source: 'acc_007', target: 'nar_003', type: 'AMPLIFIES' },
  { source: 'acc_011', target: 'nar_001', type: 'AMPLIFIES' },
  { source: 'acc_012', target: 'nar_001', type: 'AMPLIFIES' },
  { source: 'acc_009', target: 'nar_004', type: 'AMPLIFIES' },
  { source: 'acc_008', target: 'nar_002', type: 'AMPLIFIES' },
  { source: 'acc_005', target: 'nar_005', type: 'AMPLIFIES' },
  { source: 'acc_001', target: 'tag_001', type: 'TAGGED_WITH' },
  { source: 'acc_001', target: 'tag_004', type: 'TAGGED_WITH' },
  { source: 'acc_002', target: 'tag_002', type: 'TAGGED_WITH' },
  { source: 'acc_002', target: 'tag_003', type: 'TAGGED_WITH' },
  { source: 'acc_003', target: 'tag_003', type: 'TAGGED_WITH' },
  { source: 'acc_004', target: 'tag_001', type: 'TAGGED_WITH' },
  { source: 'acc_005', target: 'tag_003', type: 'TAGGED_WITH' },
  { source: 'acc_006', target: 'tag_002', type: 'TAGGED_WITH' },
  { source: 'acc_007', target: 'tag_005', type: 'TAGGED_WITH' },
  { source: 'acc_011', target: 'tag_001', type: 'TAGGED_WITH' },
  { source: 'acc_012', target: 'tag_001', type: 'TAGGED_WITH' },
  { source: 'nar_001', target: 'tag_001', type: 'SPREADS_VIA' },
  { source: 'nar_002', target: 'tag_002', type: 'SPREADS_VIA' },
  { source: 'nar_004', target: 'tag_003', type: 'SPREADS_VIA' },
  { source: 'acc_011', target: 'acc_012', type: 'PART_OF_NETWORK' },
  { source: 'acc_004', target: 'acc_005', type: 'PART_OF_NETWORK' },
]

export const ACTIVITY: ActivityItem[] = [
  { time: '09:41', alert: true, text: 'Coordination detected: @ke_observer_9 ↔ @kenyapolitics24 — 94% posting overlap over 72hrs' },
  { time: '09:38', alert: false, text: '[Election System Compromised] velocity +34% in 6hrs — 3 new amplifiers detected' },
  { time: '09:22', alert: false, text: "@NairobiTruth_KE seeded new claim: 'foreign observers pre-scripted outcome'" },
  { time: '09:11', alert: false, text: '#RutoMustGo reached peak velocity — 89,400 posts, 67% from accounts <6 months old' },
  { time: '08:55', alert: true, text: 'New cluster forming around [Ethnic Land Grievance Reframe] — 4 new micro accounts in 2hrs' },
  { time: '08:33', alert: false, text: '[Vaccine Microchip Revival] decaying — reach down 42% over 48hrs' },
  { time: '08:14', alert: false, text: '@KE_Wakili posted 14 times in 3hrs — cadence anomaly flagged' },
]

export const REVIEW_QUEUE: ReviewItem[] = [
  { id: 'rev_001', gate: 'GATE 2', verdict_tag: 'coordinated_inauthentic', target: '@ke_observer_9', confidence: 0.62, tier: 'medium',
    excerpt: 'Election was decided 6 months ago in Washington — wake up people 🇰🇪',
    reason: 'Sensitive verdict (coordination) + medium confidence', flagged_at: '09:38', model: 'claude-sonnet/post_tagger_1.2' },
  { id: 'rev_002', gate: 'GATE 2', verdict_tag: 'identity_wedge', target: '@Rift_Patriot', confidence: 0.81, tier: 'high',
    excerpt: 'Our people have been silenced for too long. The land is OURS. They know who took it.',
    reason: 'Sensitive: identity_wedge attribution requires sign-off', flagged_at: '09:11', model: 'claude-sonnet/post_tagger_1.2' },
  { id: 'rev_003', gate: 'GATE 1', verdict_tag: 'firehose_falsehood', target: '@NairobiTruth_KE', confidence: 0.74, tier: 'medium',
    excerpt: 'IMF doc leaked: KE forced to sell port. RT before they delete!!! [link]',
    reason: 'Medium confidence on firehose pattern', flagged_at: '09:22', model: 'claude-sonnet/post_tagger_1.2' },
  { id: 'rev_004', gate: 'GATE 1', verdict_tag: 'health_misinfo', target: '@KenyaWatchdog', confidence: 0.45, tier: 'low',
    excerpt: 'Why did 3 friends get sick after the booster? Just asking questions, brothers.',
    reason: 'Low confidence — needs analyst ground truth', flagged_at: '08:55', model: 'claude-sonnet/post_tagger_1.2' },
  { id: 'rev_005', gate: 'GATE 2', verdict_tag: 'coordinated_inauthentic', target: '@kenyapolitics24', confidence: 0.79, tier: 'high',
    excerpt: 'BREAKING: ELECTION IS RIGGED. EVERY KENYAN MUST KNOW THIS NOW.',
    reason: 'Coordination attribution → network cluster #C7', flagged_at: '08:33', model: 'claude-sonnet/post_tagger_1.2' },
  { id: 'rev_006', gate: 'GATE 1', verdict_tag: 'appeal_to_victimhood', target: '@nairobi_mwananchi', confidence: 0.58, tier: 'medium',
    excerpt: 'We are the victims here. They will pay for what they did to us.',
    reason: 'Medium confidence on victimhood appeal', flagged_at: '08:14', model: 'claude-sonnet/post_tagger_1.2' },
]
