# Generated by Django 5.2.14 on 2026-06-06 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_rename_chatbot_con_user_id_a1b2c3_idx_chatbot_con_user_id_187fae_idx_and_more'),
        ('orchestration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionreceipt',
            new_name='orchestrati_user_id_0eba90_idx',
            old_name='orchestration_actionreceipt_user_room_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='actionreceipt',
            unique_together={('user', 'room', 'action')},
        ),
        migrations.AddIndex(
            model_name='actionreceipt',
            index=models.Index(fields=['user', 'action', 'created_at'], name='orchestrati_user_id_677390_idx'),
        ),
    ]
