# Generated by Django 6.0.4 on 2026-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_rename_chatbot_con_user_id_a1b2c3_idx_chatbot_con_user_id_187fae_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='domain',
            field=models.CharField(blank=True, default='ops', max_length=32),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
