# Generated by Django 5.2.14 on 2026-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='ai_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
