# Generated by Django 6.0.4 on 2026-06-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugBountyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('HackerOne', 'HackerOne'), ('Bugcrowd', 'Bugcrowd'), ('Intigriti', 'Intigriti')], max_length=20)),
                ('asset_count', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('bounty_range', models.CharField(default='', max_length=100)),
                ('in_scope', models.JSONField(default=list)),
                ('out_of_scope', models.JSONField(default=list)),
                ('reward_notes', models.TextField(default='')),
                ('scan_status', models.CharField(choices=[('ready', 'Ready'), ('queued', 'Queued'), ('running', 'Running')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugBountyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('target', models.CharField(max_length=300)),
                ('bounty_kes', models.IntegerField(default=0)),
                ('platform', models.CharField(choices=[('HackerOne', 'HackerOne'), ('Bugcrowd', 'Bugcrowd'), ('Intigriti', 'Intigriti')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('triaged', 'Triaged'), ('duplicate', 'Duplicate'), ('resolved', 'Resolved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bugbounty.bugbountyprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BugBountyReportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('platform_program', models.CharField(max_length=200)),
                ('steps', models.TextField()),
                ('impact', models.TextField()),
                ('evidence_name', models.CharField(default='', max_length=200)),
                ('estimated_bounty', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='bugbounty.bugbountyprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
