# Generated by Django 6.0.4 on 2026-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbounty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugBountyWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bugbountyprogram',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bugbountyprogram',
            name='source_handle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bugbountyprogram',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugbountyreport',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bugbountyreport',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bugbountyreport',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bugbountyreport',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
