# Generated by Django 6.0.4 on 2026-08-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbounty', '0002_bugbountywebhookevent_bugbountyprogram_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugBountyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(blank=True, default='', max_length=50)),
                ('identifier', models.CharField(blank=True, default='', max_length=500)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='BugBountyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('multiplier', models.CharField(blank=True, default='', max_length=50)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='bugbounty.bugbountyprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='BugBountyOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100, unique=True)),
                ('handle', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('member_count', models.IntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugbounty_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['handle'],
            },
        ),
    ]
