# Generated by Django 5.2.14 on 2026-06-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_invite_chain_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='correctionsignal',
            new_name='users_corre_user_id_55faae_idx',
            old_name='users_corre_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='correctionsignal',
            new_name='users_corre_user_id_da7877_idx',
            old_name='users_corre_user_id_intent_idx',
        ),
        migrations.RenameIndex(
            model_name='correctionsignal',
            new_name='users_corre_correct_6de1ad_idx',
            old_name='users_corre_correction_type_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=0, help_text='DEPRECATED - Current onboarding step (0-6)'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('pro', 'Pro'), ('agency', 'Agency')], default='free', max_length=20),
        ),
    ]
